site_name: Boa 

nav:
  - Hem: ./index.md
  - Bokföring: ./bokföring.md
  - Grundbok: ./grundbok.md

plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src/boa]
